services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simple_crud
    volumes:
      - simple_crud_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simple_crud -h localhost -p 5432"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 30s
      
  app:
    image: simple-crud-prod
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
      
volumes:
  simple_crud_data: